export const hello = [
    'Empty cell of color Lavender, row 1, column 1',
    'Empty cell of color Peach Orange, row 1, column 2',
    'Empty cell of color Peach Orange, row 1, column 3',
    'Empty cell of color Peach Orange, row 1, column 4',
    'Empty cell of color Lavender, row 1, column 5',
    'Empty cell of color Soft Blue, row 1, column 6',
    'Empty cell of color Soft Blue, row 1, column 7',
    'Empty cell of color Soft Blue, row 1, column 8',
    'Empty cell of color Pastel Green, row 1, column 9',
    'Queen of color Pastel Green, row 1, column 10',
    'Empty cell of color Pastel Green, row 1, column 11',
    'Empty cell of color Lavender, row 2, column 1',
    'Empty cell of color Lavender, row 2, column 2',
    'Queen of color Peach Orange, row 2, column 3',
    'Empty cell of color Lavender, row 2, column 4',
    'Empty cell of color Lavender, row 2, column 5',
    'Empty cell of color Soft Blue, row 2, column 6',
    'Empty cell of color Soft Blue, row 2, column 7',
    'Empty cell of color Soft Blue, row 2, column 8',
    'Empty cell of color Soft Blue, row 2, column 9',
    'Empty cell of color Light Gray, row 2, column 10',
    'Empty cell of color Pastel Green, row 2, column 11',
    'Empty cell of color Vibrant Coral, row 3, column 1',
    'Empty cell of color Lavender, row 3, column 2',
    'Empty cell of color Lavender, row 3, column 3',
    'Empty cell of color Lavender, row 3, column 4',
    'Empty cell of color Soft Blue, row 3, column 5',
    'Empty cell of color Soft Blue, row 3, column 6',
    'Empty cell of color Light Gray, row 3, column 7',
    'Empty cell of color Light Gray, row 3, column 8',
    'Empty cell of color Light Gray, row 3, column 9',
    'Empty cell of color Light Gray, row 3, column 10',
    'Empty cell of color Pastel Green, row 3, column 11',
    'Empty cell of color Vibrant Coral, row 4, column 1',
    'Empty cell of color Vibrant Coral, row 4, column 2',
    'Empty cell of color Lavender, row 4, column 3',
    'Empty cell of color Soft Blue, row 4, column 4',
    'Empty cell of color Soft Blue, row 4, column 5',
    'Empty cell of color Light Gray, row 4, column 6',
    'Empty cell of color Light Gray, row 4, column 7',
    'Empty cell of color Light Gray, row 4, column 8',
    'Empty cell of color Light Gray, row 4, column 9',
    'Empty cell of color Light Gray, row 4, column 10',
    'Empty cell of color Pastel Green, row 4, column 11',
    'Empty cell of color Vibrant Coral, row 5, column 1',
    'Empty cell of color Lavender, row 5, column 2',
    'Empty cell of color Lavender, row 5, column 3',
    'Empty cell of color Lavender, row 5, column 4',
    'Empty cell of color Soft Blue, row 5, column 5',
    'Empty cell of color Light Gray, row 5, column 6',
    'Empty cell of color Light Gray, row 5, column 7',
    'Empty cell of color Lime Yellow, row 5, column 8',
    'Empty cell of color Lime Yellow, row 5, column 9',
    'Empty cell of color Lime Yellow, row 5, column 10',
    'Empty cell of color Pastel Green, row 5, column 11',
    'Empty cell of color Lavender, row 6, column 1',
    'Empty cell of color Lavender, row 6, column 2',
    'Empty cell of color Warm Beige, row 6, column 3',
    'Empty cell of color Lavender, row 6, column 4',
    'Empty cell of color Lavender, row 6, column 5',
    'Empty cell of color Light Gray, row 6, column 6',
    'Empty cell of color Lime Yellow, row 6, column 7',
    'Empty cell of color Lime Yellow, row 6, column 8',
    'Empty cell of color Lime Yellow, row 6, column 9',
    'Empty cell of color Lime Yellow, row 6, column 10',
    'Empty cell of color Lime Yellow, row 6, column 11',
    'Empty cell of color Lavender, row 7, column 1',
    'Empty cell of color Warm Beige, row 7, column 2',
    'Empty cell of color Warm Beige, row 7, column 3',
    'Empty cell of color Warm Beige, row 7, column 4',
    'Empty cell of color Lavender, row 7, column 5',
    'Empty cell of color Light Gray, row 7, column 6',
    'Empty cell of color Lime Yellow, row 7, column 7',
    'Empty cell of color Lime Yellow, row 7, column 8',
    'Empty cell of color Rose Pink, row 7, column 9',
    'Empty cell of color Lime Yellow, row 7, column 10',
    'Empty cell of color Lime Yellow, row 7, column 11',
    'Empty cell of color Muted Teal, row 8, column 1',
    'Empty cell of color Muted Teal, row 8, column 2',
    'Empty cell of color Muted Teal, row 8, column 3',
    'Empty cell of color Muted Teal, row 8, column 4',
    'Empty cell of color Light Gray, row 8, column 5',
    'Empty cell of color Light Gray, row 8, column 6',
    'Empty cell of color Lime Yellow, row 8, column 7',
    'Empty cell of color Rose Pink, row 8, column 8',
    'Empty cell of color Rose Pink, row 8, column 9',
    'Empty cell of color Rose Pink, row 8, column 10',
    'Empty cell of color Lime Yellow, row 8, column 11',
    'Empty cell of color Muted Teal, row 9, column 1',
    'Empty cell of color Muted Teal, row 9, column 2',
    'Empty cell of color Muted Teal, row 9, column 3',
    'Empty cell of color Light Gray, row 9, column 4',
    'Empty cell of color Light Gray, row 9, column 5',
    'Empty cell of color Light Gray, row 9, column 6',
    'Empty cell of color Lime Yellow, row 9, column 7',
    'Empty cell of color Lime Yellow, row 9, column 8',
    'Empty cell of color Rose Pink, row 9, column 9',
    'Empty cell of color Lime Yellow, row 9, column 10',
    'Empty cell of color Lime Yellow, row 9, column 11',
    'Empty cell of color Muted Teal, row 10, column 1',
    'Empty cell of color Muted Teal, row 10, column 2',
    'Empty cell of color Muted Teal, row 10, column 3',
    'Empty cell of color Light Gray, row 10, column 4',
    'Empty cell of color Light Gray, row 10, column 5',
    'Empty cell of color Light Gray, row 10, column 6',
    'Empty cell of color Lime Yellow, row 10, column 7',
    'Empty cell of color Lime Yellow, row 10, column 8',
    'Empty cell of color Lime Yellow, row 10, column 9',
    'Empty cell of color Lime Yellow, row 10, column 10',
    'Empty cell of color Lime Yellow, row 10, column 11',
    'Empty cell of color Muted Teal, row 11, column 1',
    'Empty cell of color Muted Teal, row 11, column 2',
    'Empty cell of color Muted Teal, row 11, column 3',
    'Empty cell of color Light Gray, row 11, column 4',
    'Empty cell of color Light Gray, row 11, column 5',
    'Empty cell of color Light Gray, row 11, column 6',
    'Empty cell of color Light Gray, row 11, column 7',
    'Empty cell of color Lime Yellow, row 11, column 8',
    'Empty cell of color Lime Yellow, row 11, column 9',
    'Empty cell of color Lime Yellow, row 11, column 10',
    'Empty cell of color Bright Cyan, row 11, column 11'
]

export const dimensions = {
    rows: 11,
    columns: 11
}

export const secondDimensions = {
    rows: 7,
    columns: 7
}

export const secondNewOne = [
    'Empty cell of color Lavender, row 1, column 1',
    'Empty cell of color Lavender, row 1, column 2',
    'Empty cell of color Lavender, row 1, column 3',
    'Queen of color Lavender, row 1, column 4',
    'Empty cell of color Lavender, row 1, column 5',
    'Empty cell of color Lavender, row 1, column 6',
    'Empty cell of color Peach Orange, row 1, column 7',
    'Empty cell of color Lavender, row 2, column 1',
    'Empty cell of color Soft Blue, row 2, column 2',
    'Empty cell of color Lavender, row 2, column 3',
    'Empty cell of color Lavender, row 2, column 4',
    'Empty cell of color Lavender, row 2, column 5',
    'Empty cell of color Peach Orange, row 2, column 6',
    'Queen of color Peach Orange, row 2, column 7',
    'Empty cell of color Soft Blue, row 3, column 1',
    'Empty cell of color Soft Blue, row 3, column 2',
    'Empty cell of color Soft Blue, row 3, column 3',
    'Empty cell of color Lavender, row 3, column 4',
    'Empty cell of color Lavender, row 3, column 5',
    'Empty cell of color Peach Orange, row 3, column 6',
    'Empty cell of color Peach Orange, row 3, column 7',
    'Empty cell of color Pastel Green, row 4, column 1',
    'Empty cell of color Light Gray, row 4, column 2',
    'Empty cell of color Light Gray, row 4, column 3',
    'Empty cell of color Light Gray, row 4, column 4',
    'Empty cell of color Light Gray, row 4, column 5',
    'Empty cell of color Light Gray, row 4, column 6',
    'Empty cell of color Peach Orange, row 4, column 7',
    'Empty cell of color Vibrant Coral, row 5, column 1',
    'Empty cell of color Vibrant Coral, row 5, column 2',
    'Empty cell of color Vibrant Coral, row 5, column 3',
    'Empty cell of color Lime Yellow, row 5, column 4',
    'Empty cell of color Light Gray, row 5, column 5',
    'Empty cell of color Peach Orange, row 5, column 6',
    'Empty cell of color Peach Orange, row 5, column 7',
    'Empty cell of color Lime Yellow, row 6, column 1',
    'Empty cell of color Vibrant Coral, row 6, column 2',
    'Empty cell of color Lime Yellow, row 6, column 3',
    'Empty cell of color Lime Yellow, row 6, column 4',
    'Empty cell of color Lime Yellow, row 6, column 5',
    'Empty cell of color Peach Orange, row 6, column 6',
    'Empty cell of color Peach Orange, row 6, column 7',
    'Empty cell of color Lime Yellow, row 7, column 1',
    'Empty cell of color Lime Yellow, row 7, column 2',
    'Empty cell of color Lime Yellow, row 7, column 3',
    'Empty cell of color Lime Yellow, row 7, column 4',
    'Empty cell of color Lime Yellow, row 7, column 5',
    'Empty cell of color Lime Yellow, row 7, column 6',
    'Empty cell of color Peach Orange, row 7, column 7'
  ]

export default hello