export const hello = [
  "Empty cell of color Lavender, row 1, column 1",
  "Empty cell of color Peach Orange, row 1, column 2",
  "Empty cell of color Peach Orange, row 1, column 3",
  "Empty cell of color Peach Orange, row 1, column 4",
  "Empty cell of color Lavender, row 1, column 5",
  "Empty cell of color Soft Blue, row 1, column 6",
  "Empty cell of color Soft Blue, row 1, column 7",
  "Empty cell of color Soft Blue, row 1, column 8",
  "Empty cell of color Pastel Green, row 1, column 9",
  "Queen of color Pastel Green, row 1, column 10",
  "Empty cell of color Pastel Green, row 1, column 11",
  "Empty cell of color Lavender, row 2, column 1",
  "Empty cell of color Lavender, row 2, column 2",
  "Queen of color Peach Orange, row 2, column 3",
  "Empty cell of color Lavender, row 2, column 4",
  "Empty cell of color Lavender, row 2, column 5",
  "Empty cell of color Soft Blue, row 2, column 6",
  "Empty cell of color Soft Blue, row 2, column 7",
  "Empty cell of color Soft Blue, row 2, column 8",
  "Empty cell of color Soft Blue, row 2, column 9",
  "Empty cell of color Light Gray, row 2, column 10",
  "Empty cell of color Pastel Green, row 2, column 11",
  "Empty cell of color Vibrant Coral, row 3, column 1",
  "Empty cell of color Lavender, row 3, column 2",
  "Empty cell of color Lavender, row 3, column 3",
  "Empty cell of color Lavender, row 3, column 4",
  "Empty cell of color Soft Blue, row 3, column 5",
  "Empty cell of color Soft Blue, row 3, column 6",
  "Empty cell of color Light Gray, row 3, column 7",
  "Empty cell of color Light Gray, row 3, column 8",
  "Empty cell of color Light Gray, row 3, column 9",
  "Empty cell of color Light Gray, row 3, column 10",
  "Empty cell of color Pastel Green, row 3, column 11",
  "Empty cell of color Vibrant Coral, row 4, column 1",
  "Empty cell of color Vibrant Coral, row 4, column 2",
  "Empty cell of color Lavender, row 4, column 3",
  "Empty cell of color Soft Blue, row 4, column 4",
  "Empty cell of color Soft Blue, row 4, column 5",
  "Empty cell of color Light Gray, row 4, column 6",
  "Empty cell of color Light Gray, row 4, column 7",
  "Empty cell of color Light Gray, row 4, column 8",
  "Empty cell of color Light Gray, row 4, column 9",
  "Empty cell of color Light Gray, row 4, column 10",
  "Empty cell of color Pastel Green, row 4, column 11",
  "Empty cell of color Vibrant Coral, row 5, column 1",
  "Empty cell of color Lavender, row 5, column 2",
  "Empty cell of color Lavender, row 5, column 3",
  "Empty cell of color Lavender, row 5, column 4",
  "Empty cell of color Soft Blue, row 5, column 5",
  "Empty cell of color Light Gray, row 5, column 6",
  "Empty cell of color Light Gray, row 5, column 7",
  "Empty cell of color Lime Yellow, row 5, column 8",
  "Empty cell of color Lime Yellow, row 5, column 9",
  "Empty cell of color Lime Yellow, row 5, column 10",
  "Empty cell of color Pastel Green, row 5, column 11",
  "Empty cell of color Lavender, row 6, column 1",
  "Empty cell of color Lavender, row 6, column 2",
  "Empty cell of color Warm Beige, row 6, column 3",
  "Empty cell of color Lavender, row 6, column 4",
  "Empty cell of color Lavender, row 6, column 5",
  "Empty cell of color Light Gray, row 6, column 6",
  "Empty cell of color Lime Yellow, row 6, column 7",
  "Empty cell of color Lime Yellow, row 6, column 8",
  "Empty cell of color Lime Yellow, row 6, column 9",
  "Empty cell of color Lime Yellow, row 6, column 10",
  "Empty cell of color Lime Yellow, row 6, column 11",
  "Empty cell of color Lavender, row 7, column 1",
  "Empty cell of color Warm Beige, row 7, column 2",
  "Empty cell of color Warm Beige, row 7, column 3",
  "Empty cell of color Warm Beige, row 7, column 4",
  "Empty cell of color Lavender, row 7, column 5",
  "Empty cell of color Light Gray, row 7, column 6",
  "Empty cell of color Lime Yellow, row 7, column 7",
  "Empty cell of color Lime Yellow, row 7, column 8",
  "Empty cell of color Rose Pink, row 7, column 9",
  "Empty cell of color Lime Yellow, row 7, column 10",
  "Empty cell of color Lime Yellow, row 7, column 11",
  "Empty cell of color Muted Teal, row 8, column 1",
  "Empty cell of color Muted Teal, row 8, column 2",
  "Empty cell of color Muted Teal, row 8, column 3",
  "Empty cell of color Muted Teal, row 8, column 4",
  "Empty cell of color Light Gray, row 8, column 5",
  "Empty cell of color Light Gray, row 8, column 6",
  "Empty cell of color Lime Yellow, row 8, column 7",
  "Empty cell of color Rose Pink, row 8, column 8",
  "Empty cell of color Rose Pink, row 8, column 9",
  "Empty cell of color Rose Pink, row 8, column 10",
  "Empty cell of color Lime Yellow, row 8, column 11",
  "Empty cell of color Muted Teal, row 9, column 1",
  "Empty cell of color Muted Teal, row 9, column 2",
  "Empty cell of color Muted Teal, row 9, column 3",
  "Empty cell of color Light Gray, row 9, column 4",
  "Empty cell of color Light Gray, row 9, column 5",
  "Empty cell of color Light Gray, row 9, column 6",
  "Empty cell of color Lime Yellow, row 9, column 7",
  "Empty cell of color Lime Yellow, row 9, column 8",
  "Empty cell of color Rose Pink, row 9, column 9",
  "Empty cell of color Lime Yellow, row 9, column 10",
  "Empty cell of color Lime Yellow, row 9, column 11",
  "Empty cell of color Muted Teal, row 10, column 1",
  "Empty cell of color Muted Teal, row 10, column 2",
  "Empty cell of color Muted Teal, row 10, column 3",
  "Empty cell of color Light Gray, row 10, column 4",
  "Empty cell of color Light Gray, row 10, column 5",
  "Empty cell of color Light Gray, row 10, column 6",
  "Empty cell of color Lime Yellow, row 10, column 7",
  "Empty cell of color Lime Yellow, row 10, column 8",
  "Empty cell of color Lime Yellow, row 10, column 9",
  "Empty cell of color Lime Yellow, row 10, column 10",
  "Empty cell of color Lime Yellow, row 10, column 11",
  "Empty cell of color Muted Teal, row 11, column 1",
  "Empty cell of color Muted Teal, row 11, column 2",
  "Empty cell of color Muted Teal, row 11, column 3",
  "Empty cell of color Light Gray, row 11, column 4",
  "Empty cell of color Light Gray, row 11, column 5",
  "Empty cell of color Light Gray, row 11, column 6",
  "Empty cell of color Light Gray, row 11, column 7",
  "Empty cell of color Lime Yellow, row 11, column 8",
  "Empty cell of color Lime Yellow, row 11, column 9",
  "Empty cell of color Lime Yellow, row 11, column 10",
  "Empty cell of color Bright Cyan, row 11, column 11",
];

export const secondNewOne = [
  "Empty cell of color Lavender, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Lavender, row 1, column 3",
  "Queen of color Lavender, row 1, column 4",
  "Empty cell of color Lavender, row 1, column 5",
  "Empty cell of color Lavender, row 1, column 6",
  "Empty cell of color Peach Orange, row 1, column 7",
  "Empty cell of color Lavender, row 2, column 1",
  "Empty cell of color Soft Blue, row 2, column 2",
  "Empty cell of color Lavender, row 2, column 3",
  "Empty cell of color Lavender, row 2, column 4",
  "Empty cell of color Lavender, row 2, column 5",
  "Empty cell of color Peach Orange, row 2, column 6",
  "Queen of color Peach Orange, row 2, column 7",
  "Empty cell of color Soft Blue, row 3, column 1",
  "Empty cell of color Soft Blue, row 3, column 2",
  "Empty cell of color Soft Blue, row 3, column 3",
  "Empty cell of color Lavender, row 3, column 4",
  "Empty cell of color Lavender, row 3, column 5",
  "Empty cell of color Peach Orange, row 3, column 6",
  "Empty cell of color Peach Orange, row 3, column 7",
  "Empty cell of color Pastel Green, row 4, column 1",
  "Empty cell of color Light Gray, row 4, column 2",
  "Empty cell of color Light Gray, row 4, column 3",
  "Empty cell of color Light Gray, row 4, column 4",
  "Empty cell of color Light Gray, row 4, column 5",
  "Empty cell of color Light Gray, row 4, column 6",
  "Empty cell of color Peach Orange, row 4, column 7",
  "Empty cell of color Vibrant Coral, row 5, column 1",
  "Empty cell of color Vibrant Coral, row 5, column 2",
  "Empty cell of color Vibrant Coral, row 5, column 3",
  "Empty cell of color Lime Yellow, row 5, column 4",
  "Empty cell of color Light Gray, row 5, column 5",
  "Empty cell of color Peach Orange, row 5, column 6",
  "Empty cell of color Peach Orange, row 5, column 7",
  "Empty cell of color Lime Yellow, row 6, column 1",
  "Empty cell of color Vibrant Coral, row 6, column 2",
  "Empty cell of color Lime Yellow, row 6, column 3",
  "Empty cell of color Lime Yellow, row 6, column 4",
  "Empty cell of color Lime Yellow, row 6, column 5",
  "Empty cell of color Peach Orange, row 6, column 6",
  "Empty cell of color Peach Orange, row 6, column 7",
  "Empty cell of color Lime Yellow, row 7, column 1",
  "Empty cell of color Lime Yellow, row 7, column 2",
  "Empty cell of color Lime Yellow, row 7, column 3",
  "Empty cell of color Lime Yellow, row 7, column 4",
  "Empty cell of color Lime Yellow, row 7, column 5",
  "Empty cell of color Lime Yellow, row 7, column 6",
  "Empty cell of color Peach Orange, row 7, column 7",
];

export const got3Minutes = [
  "Empty cell of color Vibrant Coral, row 1, column 1",
  "Empty cell of color Vibrant Coral, row 1, column 2",
  "Empty cell of color Vibrant Coral, row 1, column 3",
  "Empty cell of color Vibrant Coral, row 1, column 4",
  "Empty cell of color Vibrant Coral, row 1, column 5",
  "Empty cell of color Vibrant Coral, row 1, column 6",
  "Queen of color Peach Orange, row 1, column 7",
  "Empty cell of color Peach Orange, row 1, column 8",
  "Empty cell of color Peach Orange, row 1, column 9",
  "Empty cell of color Vibrant Coral, row 2, column 1",
  "Empty cell of color Soft Blue, row 2, column 2",
  "Empty cell of color Soft Blue, row 2, column 3",
  "Empty cell of color Soft Blue, row 2, column 4",
  "Empty cell of color Soft Blue, row 2, column 5",
  "Empty cell of color Soft Blue, row 2, column 6",
  "Empty cell of color Soft Blue, row 2, column 7",
  "Empty cell of color Soft Blue, row 2, column 8",
  "Queen of color Pastel Green, row 2, column 9",
  "Empty cell of color Vibrant Coral, row 3, column 1",
  "Empty cell of color Soft Blue, row 3, column 2",
  "Empty cell of color Light Gray, row 3, column 3",
  "Empty cell of color Lavender, row 3, column 4",
  "Empty cell of color Lavender, row 3, column 5",
  "Empty cell of color Lavender, row 3, column 6",
  "Empty cell of color Pastel Green, row 3, column 7",
  "Empty cell of color Pastel Green, row 3, column 8",
  "Empty cell of color Pastel Green, row 3, column 9",
  "Empty cell of color Vibrant Coral, row 4, column 1",
  "Empty cell of color Soft Blue, row 4, column 2",
  "Empty cell of color Light Gray, row 4, column 3",
  "Empty cell of color Light Gray, row 4, column 4",
  "Empty cell of color Light Gray, row 4, column 5",
  "Empty cell of color Lavender, row 4, column 6",
  "Empty cell of color Pastel Green, row 4, column 7",
  "Empty cell of color Pastel Green, row 4, column 8",
  "Empty cell of color Pastel Green, row 4, column 9",
  "Empty cell of color Vibrant Coral, row 5, column 1",
  "Empty cell of color Soft Blue, row 5, column 2",
  "Empty cell of color Soft Blue, row 5, column 3",
  "Empty cell of color Soft Blue, row 5, column 4",
  "Empty cell of color Soft Blue, row 5, column 5",
  "Empty cell of color Soft Blue, row 5, column 6",
  "Empty cell of color Soft Blue, row 5, column 7",
  "Empty cell of color Soft Blue, row 5, column 8",
  "Empty cell of color Lime Yellow, row 5, column 9",
  "Empty cell of color Vibrant Coral, row 6, column 1",
  "Empty cell of color Rose Pink, row 6, column 2",
  "Empty cell of color Rose Pink, row 6, column 3",
  "Empty cell of color Rose Pink, row 6, column 4",
  "Empty cell of color Rose Pink, row 6, column 5",
  "Empty cell of color Rose Pink, row 6, column 6",
  "Empty cell of color Rose Pink, row 6, column 7",
  "Empty cell of color Soft Blue, row 6, column 8",
  "Empty cell of color Lime Yellow, row 6, column 9",
  "Empty cell of color Vibrant Coral, row 7, column 1",
  "Empty cell of color Rose Pink, row 7, column 2",
  "Empty cell of color Rose Pink, row 7, column 3",
  "Empty cell of color Rose Pink, row 7, column 4",
  "Empty cell of color Rose Pink, row 7, column 5",
  "Empty cell of color Warm Beige, row 7, column 6",
  "Empty cell of color Warm Beige, row 7, column 7",
  "Empty cell of color Soft Blue, row 7, column 8",
  "Empty cell of color Lime Yellow, row 7, column 9",
  "Empty cell of color Vibrant Coral, row 8, column 1",
  "Empty cell of color Soft Blue, row 8, column 2",
  "Empty cell of color Soft Blue, row 8, column 3",
  "Empty cell of color Soft Blue, row 8, column 4",
  "Empty cell of color Soft Blue, row 8, column 5",
  "Empty cell of color Soft Blue, row 8, column 6",
  "Empty cell of color Soft Blue, row 8, column 7",
  "Empty cell of color Soft Blue, row 8, column 8",
  "Empty cell of color Lime Yellow, row 8, column 9",
  "Empty cell of color Vibrant Coral, row 9, column 1",
  "Empty cell of color Vibrant Coral, row 9, column 2",
  "Empty cell of color Vibrant Coral, row 9, column 3",
  "Empty cell of color Vibrant Coral, row 9, column 4",
  "Empty cell of color Lime Yellow, row 9, column 5",
  "Empty cell of color Lime Yellow, row 9, column 6",
  "Empty cell of color Lime Yellow, row 9, column 7",
  "Empty cell of color Lime Yellow, row 9, column 8",
  "Empty cell of color Lime Yellow, row 9, column 9",
];

export const mamoudou = [
  "Empty cell of color Peach Orange, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Soft Blue, row 1, column 3",
  "Empty cell of color Soft Blue, row 1, column 4",
  "Queen of color Soft Blue, row 1, column 5",
  "Empty cell of color Soft Blue, row 1, column 6",
  "Empty cell of color Rose Pink, row 1, column 7",
  "Empty cell of color Light Gray, row 1, column 8",
  "Empty cell of color Light Gray, row 1, column 9",
  "Empty cell of color Light Gray, row 1, column 10",
  "Empty cell of color Peach Orange, row 2, column 1",
  "Empty cell of color Lavender, row 2, column 2",
  "Queen of color Lavender, row 2, column 3",
  "Empty cell of color Lavender, row 2, column 4",
  "Empty cell of color Soft Blue, row 2, column 5",
  "Empty cell of color Rose Pink, row 2, column 6",
  "Empty cell of color Rose Pink, row 2, column 7",
  "Empty cell of color Rose Pink, row 2, column 8",
  "Empty cell of color Light Gray, row 2, column 9",
  "Empty cell of color Light Gray, row 2, column 10",
  "Empty cell of color Peach Orange, row 3, column 1",
  "Empty cell of color Lavender, row 3, column 2",
  "Empty cell of color Vibrant Coral, row 3, column 3",
  "Empty cell of color Lime Yellow, row 3, column 4",
  "Empty cell of color Lime Yellow, row 3, column 5",
  "Empty cell of color Rose Pink, row 3, column 6",
  "Empty cell of color Light Gray, row 3, column 7",
  "Empty cell of color Light Gray, row 3, column 8",
  "Empty cell of color Light Gray, row 3, column 9",
  "Empty cell of color Light Gray, row 3, column 10",
  "Empty cell of color Peach Orange, row 4, column 1",
  "Empty cell of color Peach Orange, row 4, column 2",
  "Empty cell of color Vibrant Coral, row 4, column 3",
  "Empty cell of color Lime Yellow, row 4, column 4",
  "Empty cell of color Lime Yellow, row 4, column 5",
  "Empty cell of color Lime Yellow, row 4, column 6",
  "Empty cell of color Lime Yellow, row 4, column 7",
  "Empty cell of color Lime Yellow, row 4, column 8",
  "Empty cell of color Light Gray, row 4, column 9",
  "Empty cell of color Light Gray, row 4, column 10",
  "Empty cell of color Muted Teal, row 5, column 1",
  "Empty cell of color Peach Orange, row 5, column 2",
  "Empty cell of color Vibrant Coral, row 5, column 3",
  "Empty cell of color Lime Yellow, row 5, column 4",
  "Empty cell of color Pastel Green, row 5, column 5",
  "Empty cell of color Pastel Green, row 5, column 6",
  "Empty cell of color Pastel Green, row 5, column 7",
  "Empty cell of color Pastel Green, row 5, column 8",
  "Empty cell of color Pastel Green, row 5, column 9",
  "Empty cell of color Pastel Green, row 5, column 10",
  "Empty cell of color Muted Teal, row 6, column 1",
  "Empty cell of color Muted Teal, row 6, column 2",
  "Empty cell of color Vibrant Coral, row 6, column 3",
  "Empty cell of color Lime Yellow, row 6, column 4",
  "Empty cell of color Vibrant Coral, row 6, column 5",
  "Empty cell of color Pastel Green, row 6, column 6",
  "Empty cell of color Vibrant Coral, row 6, column 7",
  "Empty cell of color Pastel Green, row 6, column 8",
  "Empty cell of color Vibrant Coral, row 6, column 9",
  "Empty cell of color Pastel Green, row 6, column 10",
  "Empty cell of color Muted Teal, row 7, column 1",
  "Empty cell of color Vibrant Coral, row 7, column 2",
  "Empty cell of color Vibrant Coral, row 7, column 3",
  "Empty cell of color Vibrant Coral, row 7, column 4",
  "Empty cell of color Vibrant Coral, row 7, column 5",
  "Empty cell of color Vibrant Coral, row 7, column 6",
  "Empty cell of color Vibrant Coral, row 7, column 7",
  "Empty cell of color Vibrant Coral, row 7, column 8",
  "Empty cell of color Vibrant Coral, row 7, column 9",
  "Empty cell of color Pastel Green, row 7, column 10",
  "Empty cell of color Muted Teal, row 8, column 1",
  "Empty cell of color Vibrant Coral, row 8, column 2",
  "Empty cell of color Vibrant Coral, row 8, column 3",
  "Empty cell of color Vibrant Coral, row 8, column 4",
  "Empty cell of color Vibrant Coral, row 8, column 5",
  "Empty cell of color Vibrant Coral, row 8, column 6",
  "Empty cell of color Vibrant Coral, row 8, column 7",
  "Empty cell of color Vibrant Coral, row 8, column 8",
  "Empty cell of color Vibrant Coral, row 8, column 9",
  "Empty cell of color Warm Beige, row 8, column 10",
  "Empty cell of color Muted Teal, row 9, column 1",
  "Empty cell of color Muted Teal, row 9, column 2",
  "Empty cell of color Vibrant Coral, row 9, column 3",
  "Empty cell of color Vibrant Coral, row 9, column 4",
  "Empty cell of color Vibrant Coral, row 9, column 5",
  "Empty cell of color Vibrant Coral, row 9, column 6",
  "Empty cell of color Vibrant Coral, row 9, column 7",
  "Empty cell of color Vibrant Coral, row 9, column 8",
  "Empty cell of color Warm Beige, row 9, column 9",
  "Empty cell of color Warm Beige, row 9, column 10",
  "Empty cell of color Muted Teal, row 10, column 1",
  "Empty cell of color Muted Teal, row 10, column 2",
  "Empty cell of color Muted Teal, row 10, column 3",
  "Empty cell of color Muted Teal, row 10, column 4",
  "Empty cell of color Muted Teal, row 10, column 5",
  "Empty cell of color Muted Teal, row 10, column 6",
  "Empty cell of color Muted Teal, row 10, column 7",
  "Empty cell of color Warm Beige, row 10, column 8",
  "Empty cell of color Warm Beige, row 10, column 9",
  "Empty cell of color Warm Beige, row 10, column 10",
];

export const marmoush = [
  "Empty cell of color Muted Teal, row 1, column 1",
  "Empty cell of color Muted Teal, row 1, column 2",
  "Empty cell of color Muted Teal, row 1, column 3",
  "Empty cell of color Peach Orange, row 1, column 4",
  "Empty cell of color Peach Orange, row 1, column 5",
  "Empty cell of color Peach Orange, row 1, column 6",
  "Empty cell of color Peach Orange, row 1, column 7",
  "Queen of color Soft Blue, row 1, column 8",
  "Empty cell of color Soft Blue, row 1, column 9",
  "Empty cell of color Soft Blue, row 1, column 10",
  "Empty cell of color Muted Teal, row 2, column 1",
  "Empty cell of color Rose Pink, row 2, column 2",
  "Queen of color Peach Orange, row 2, column 3",
  "Empty cell of color Peach Orange, row 2, column 4",
  "Empty cell of color Light Gray, row 2, column 5",
  "Empty cell of color Rose Pink, row 2, column 6",
  "Empty cell of color Peach Orange, row 2, column 7",
  "Empty cell of color Rose Pink, row 2, column 8",
  "Empty cell of color Lime Yellow, row 2, column 9",
  "Empty cell of color Soft Blue, row 2, column 10",
  "Empty cell of color Muted Teal, row 3, column 1",
  "Empty cell of color Rose Pink, row 3, column 2",
  "Empty cell of color Rose Pink, row 3, column 3",
  "Empty cell of color Light Gray, row 3, column 4",
  "Empty cell of color Light Gray, row 3, column 5",
  "Empty cell of color Rose Pink, row 3, column 6",
  "Empty cell of color Rose Pink, row 3, column 7",
  "Empty cell of color Rose Pink, row 3, column 8",
  "Empty cell of color Lime Yellow, row 3, column 9",
  "Empty cell of color Soft Blue, row 3, column 10",
  "Empty cell of color Muted Teal, row 4, column 1",
  "Empty cell of color Rose Pink, row 4, column 2",
  "Empty cell of color Rose Pink, row 4, column 3",
  "Empty cell of color Rose Pink, row 4, column 4",
  "Empty cell of color Light Gray, row 4, column 5",
  "Empty cell of color Vibrant Coral, row 4, column 6",
  "Empty cell of color Rose Pink, row 4, column 7",
  "Empty cell of color Rose Pink, row 4, column 8",
  "Empty cell of color Lime Yellow, row 4, column 9",
  "Empty cell of color Lime Yellow, row 4, column 10",
  "Empty cell of color Muted Teal, row 5, column 1",
  "Empty cell of color Rose Pink, row 5, column 2",
  "Empty cell of color Muted Teal, row 5, column 3",
  "Empty cell of color Rose Pink, row 5, column 4",
  "Empty cell of color Rose Pink, row 5, column 5",
  "Empty cell of color Vibrant Coral, row 5, column 6",
  "Empty cell of color Vibrant Coral, row 5, column 7",
  "Empty cell of color Rose Pink, row 5, column 8",
  "Empty cell of color Rose Pink, row 5, column 9",
  "Empty cell of color Rose Pink, row 5, column 10",
  "Empty cell of color Muted Teal, row 6, column 1",
  "Empty cell of color Muted Teal, row 6, column 2",
  "Empty cell of color Muted Teal, row 6, column 3",
  "Empty cell of color Rose Pink, row 6, column 4",
  "Empty cell of color Rose Pink, row 6, column 5",
  "Empty cell of color Rose Pink, row 6, column 6",
  "Empty cell of color Vibrant Coral, row 6, column 7",
  "Empty cell of color Vibrant Coral, row 6, column 8",
  "Empty cell of color Rose Pink, row 6, column 9",
  "Empty cell of color Rose Pink, row 6, column 10",
  "Empty cell of color Muted Teal, row 7, column 1",
  "Empty cell of color Muted Teal, row 7, column 2",
  "Empty cell of color Rose Pink, row 7, column 3",
  "Empty cell of color Rose Pink, row 7, column 4",
  "Empty cell of color Warm Beige, row 7, column 5",
  "Empty cell of color Rose Pink, row 7, column 6",
  "Empty cell of color Rose Pink, row 7, column 7",
  "Empty cell of color Vibrant Coral, row 7, column 8",
  "Empty cell of color Vibrant Coral, row 7, column 9",
  "Empty cell of color Rose Pink, row 7, column 10",
  "Empty cell of color Muted Teal, row 8, column 1",
  "Empty cell of color Rose Pink, row 8, column 2",
  "Empty cell of color Rose Pink, row 8, column 3",
  "Empty cell of color Rose Pink, row 8, column 4",
  "Empty cell of color Warm Beige, row 8, column 5",
  "Empty cell of color Warm Beige, row 8, column 6",
  "Empty cell of color Rose Pink, row 8, column 7",
  "Empty cell of color Rose Pink, row 8, column 8",
  "Empty cell of color Rose Pink, row 8, column 9",
  "Empty cell of color Rose Pink, row 8, column 10",
  "Empty cell of color Muted Teal, row 9, column 1",
  "Empty cell of color Rose Pink, row 9, column 2",
  "Empty cell of color Muted Teal, row 9, column 3",
  "Empty cell of color Rose Pink, row 9, column 4",
  "Empty cell of color Pastel Green, row 9, column 5",
  "Empty cell of color Warm Beige, row 9, column 6",
  "Empty cell of color Warm Beige, row 9, column 7",
  "Empty cell of color Rose Pink, row 9, column 8",
  "Empty cell of color Lavender, row 9, column 9",
  "Empty cell of color Rose Pink, row 9, column 10",
  "Empty cell of color Muted Teal, row 10, column 1",
  "Empty cell of color Muted Teal, row 10, column 2",
  "Empty cell of color Muted Teal, row 10, column 3",
  "Empty cell of color Pastel Green, row 10, column 4",
  "Empty cell of color Pastel Green, row 10, column 5",
  "Empty cell of color Pastel Green, row 10, column 6",
  "Empty cell of color Lavender, row 10, column 7",
  "Empty cell of color Lavender, row 10, column 8",
  "Empty cell of color Lavender, row 10, column 9",
  "Empty cell of color Rose Pink, row 10, column 10",
];

export const sad = [
  "Empty cell of color Lavender, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Peach Orange, row 1, column 3",
  "Queen of color Peach Orange, row 1, column 4",
  "Empty cell of color Peach Orange, row 1, column 5",
  "Empty cell of color Peach Orange, row 1, column 6",
  "Empty cell of color Peach Orange, row 1, column 7",
  "Empty cell of color Peach Orange, row 1, column 8",
  "Empty cell of color Lavender, row 2, column 1",
  "Empty cell of color Soft Blue, row 2, column 2",
  "Empty cell of color Soft Blue, row 2, column 3",
  "Empty cell of color Soft Blue, row 2, column 4",
  "Empty cell of color Pastel Green, row 2, column 5",
  "Queen of color Light Gray, row 2, column 6",
  "Empty cell of color Light Gray, row 2, column 7",
  "Empty cell of color Peach Orange, row 2, column 8",
  "Empty cell of color Lavender, row 3, column 1",
  "Empty cell of color Soft Blue, row 3, column 2",
  "Empty cell of color Vibrant Coral, row 3, column 3",
  "Empty cell of color Vibrant Coral, row 3, column 4",
  "Empty cell of color Pastel Green, row 3, column 5",
  "Empty cell of color Pastel Green, row 3, column 6",
  "Empty cell of color Light Gray, row 3, column 7",
  "Empty cell of color Peach Orange, row 3, column 8",
  "Empty cell of color Lavender, row 4, column 1",
  "Empty cell of color Lavender, row 4, column 2",
  "Empty cell of color Lavender, row 4, column 3",
  "Empty cell of color Vibrant Coral, row 4, column 4",
  "Empty cell of color Vibrant Coral, row 4, column 5",
  "Empty cell of color Pastel Green, row 4, column 6",
  "Empty cell of color Pastel Green, row 4, column 7",
  "Empty cell of color Peach Orange, row 4, column 8",
  "Empty cell of color Lime Yellow, row 5, column 1",
  "Empty cell of color Lavender, row 5, column 2",
  "Empty cell of color Lavender, row 5, column 3",
  "Empty cell of color Lavender, row 5, column 4",
  "Empty cell of color Vibrant Coral, row 5, column 5",
  "Empty cell of color Vibrant Coral, row 5, column 6",
  "Empty cell of color Peach Orange, row 5, column 7",
  "Empty cell of color Peach Orange, row 5, column 8",
  "Empty cell of color Lime Yellow, row 6, column 1",
  "Empty cell of color Warm Beige, row 6, column 2",
  "Empty cell of color Lavender, row 6, column 3",
  "Empty cell of color Lavender, row 6, column 4",
  "Empty cell of color Lavender, row 6, column 5",
  "Empty cell of color Vibrant Coral, row 6, column 6",
  "Empty cell of color Peach Orange, row 6, column 7",
  "Empty cell of color Peach Orange, row 6, column 8",
  "Empty cell of color Lime Yellow, row 7, column 1",
  "Empty cell of color Warm Beige, row 7, column 2",
  "Empty cell of color Warm Beige, row 7, column 3",
  "Empty cell of color Lavender, row 7, column 4",
  "Empty cell of color Lavender, row 7, column 5",
  "Empty cell of color Peach Orange, row 7, column 6",
  "Empty cell of color Peach Orange, row 7, column 7",
  "Empty cell of color Lavender, row 7, column 8",
  "Empty cell of color Lime Yellow, row 8, column 1",
  "Empty cell of color Lime Yellow, row 8, column 2",
  "Empty cell of color Lime Yellow, row 8, column 3",
  "Empty cell of color Lime Yellow, row 8, column 4",
  "Empty cell of color Lavender, row 8, column 5",
  "Empty cell of color Lavender, row 8, column 6",
  "Empty cell of color Lavender, row 8, column 7",
  "Empty cell of color Lavender, row 8, column 8",
];

export const ramadandayone = [
  "Empty cell of color Pastel Green, row 1, column 1",
  "Empty cell of color Peach Orange, row 1, column 2",
  "Empty cell of color Peach Orange, row 1, column 3",
  "Queen of color Soft Blue, row 1, column 4",
  "Empty cell of color Soft Blue, row 1, column 5",
  "Empty cell of color Soft Blue, row 1, column 6",
  "Empty cell of color Peach Orange, row 1, column 7",
  "Empty cell of color Peach Orange, row 1, column 8",
  "Empty cell of color Peach Orange, row 1, column 9",
  "Empty cell of color Pastel Green, row 2, column 1",
  "Empty cell of color Peach Orange, row 2, column 2",
  "Empty cell of color Peach Orange, row 2, column 3",
  "Empty cell of color Soft Blue, row 2, column 4",
  "Empty cell of color Lavender, row 2, column 5",
  "Empty cell of color Soft Blue, row 2, column 6",
  "Empty cell of color Peach Orange, row 2, column 7",
  "Queen of color Peach Orange, row 2, column 8",
  "Empty cell of color Peach Orange, row 2, column 9",
  "Empty cell of color Pastel Green, row 3, column 1",
  "Empty cell of color Pastel Green, row 3, column 2",
  "Empty cell of color Peach Orange, row 3, column 3",
  "Empty cell of color Peach Orange, row 3, column 4",
  "Empty cell of color Lavender, row 3, column 5",
  "Empty cell of color Lavender, row 3, column 6",
  "Empty cell of color Peach Orange, row 3, column 7",
  "Empty cell of color Peach Orange, row 3, column 8",
  "Empty cell of color Peach Orange, row 3, column 9",
  "Empty cell of color Pastel Green, row 4, column 1",
  "Empty cell of color Pastel Green, row 4, column 2",
  "Empty cell of color Pastel Green, row 4, column 3",
  "Empty cell of color Peach Orange, row 4, column 4",
  "Empty cell of color Peach Orange, row 4, column 5",
  "Empty cell of color Lavender, row 4, column 6",
  "Empty cell of color Peach Orange, row 4, column 7",
  "Empty cell of color Peach Orange, row 4, column 8",
  "Empty cell of color Light Gray, row 4, column 9",
  "Empty cell of color Pastel Green, row 5, column 1",
  "Empty cell of color Pastel Green, row 5, column 2",
  "Empty cell of color Vibrant Coral, row 5, column 3",
  "Empty cell of color Peach Orange, row 5, column 4",
  "Empty cell of color Peach Orange, row 5, column 5",
  "Empty cell of color Lavender, row 5, column 6",
  "Empty cell of color Peach Orange, row 5, column 7",
  "Empty cell of color Peach Orange, row 5, column 8",
  "Empty cell of color Light Gray, row 5, column 9",
  "Empty cell of color Pastel Green, row 6, column 1",
  "Empty cell of color Pastel Green, row 6, column 2",
  "Empty cell of color Vibrant Coral, row 6, column 3",
  "Empty cell of color Peach Orange, row 6, column 4",
  "Empty cell of color Peach Orange, row 6, column 5",
  "Empty cell of color Peach Orange, row 6, column 6",
  "Empty cell of color Peach Orange, row 6, column 7",
  "Empty cell of color Light Gray, row 6, column 8",
  "Empty cell of color Light Gray, row 6, column 9",
  "Empty cell of color Pastel Green, row 7, column 1",
  "Empty cell of color Vibrant Coral, row 7, column 2",
  "Empty cell of color Vibrant Coral, row 7, column 3",
  "Empty cell of color Peach Orange, row 7, column 4",
  "Empty cell of color Peach Orange, row 7, column 5",
  "Empty cell of color Peach Orange, row 7, column 6",
  "Empty cell of color Lime Yellow, row 7, column 7",
  "Empty cell of color Light Gray, row 7, column 8",
  "Empty cell of color Lime Yellow, row 7, column 9",
  "Empty cell of color Warm Beige, row 8, column 1",
  "Empty cell of color Vibrant Coral, row 8, column 2",
  "Empty cell of color Warm Beige, row 8, column 3",
  "Empty cell of color Peach Orange, row 8, column 4",
  "Empty cell of color Peach Orange, row 8, column 5",
  "Empty cell of color Rose Pink, row 8, column 6",
  "Empty cell of color Lime Yellow, row 8, column 7",
  "Empty cell of color Lime Yellow, row 8, column 8",
  "Empty cell of color Lime Yellow, row 8, column 9",
  "Empty cell of color Warm Beige, row 9, column 1",
  "Empty cell of color Warm Beige, row 9, column 2",
  "Empty cell of color Warm Beige, row 9, column 3",
  "Empty cell of color Peach Orange, row 9, column 4",
  "Empty cell of color Peach Orange, row 9, column 5",
  "Empty cell of color Rose Pink, row 9, column 6",
  "Empty cell of color Rose Pink, row 9, column 7",
  "Empty cell of color Rose Pink, row 9, column 8",
  "Empty cell of color Rose Pink, row 9, column 9",
];

export const secondDayOfRamadan = [
  "Empty cell of color Lavender, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Lavender, row 1, column 3",
  "Empty cell of color Lavender, row 1, column 4",
  "Empty cell of color Rose Pink, row 1, column 5",
  "Empty cell of color Rose Pink, row 1, column 6",
  "Empty cell of color Warm Beige, row 1, column 7",
  "Queen of color Pastel Green, row 1, column 8",
  "Empty cell of color Pastel Green, row 1, column 9",
  "Empty cell of color Pastel Green, row 1, column 10",
  "Empty cell of color Lavender, row 2, column 1",
  "Empty cell of color Lavender, row 2, column 2",
  "Empty cell of color Lavender, row 2, column 3",
  "Empty cell of color Lavender, row 2, column 4",
  "Queen of color Rose Pink, row 2, column 5",
  "Empty cell of color Rose Pink, row 2, column 6",
  "Empty cell of color Warm Beige, row 2, column 7",
  "Empty cell of color Warm Beige, row 2, column 8",
  "Empty cell of color Light Gray, row 2, column 9",
  "Empty cell of color Pastel Green, row 2, column 10",
  "Empty cell of color Lavender, row 3, column 1",
  "Empty cell of color Vibrant Coral, row 3, column 2",
  "Empty cell of color Vibrant Coral, row 3, column 3",
  "Empty cell of color Lime Yellow, row 3, column 4",
  "Empty cell of color Lime Yellow, row 3, column 5",
  "Empty cell of color Lime Yellow, row 3, column 6",
  "Empty cell of color Lime Yellow, row 3, column 7",
  "Empty cell of color Warm Beige, row 3, column 8",
  "Empty cell of color Light Gray, row 3, column 9",
  "Empty cell of color Pastel Green, row 3, column 10",
  "Empty cell of color Lavender, row 4, column 1",
  "Empty cell of color Vibrant Coral, row 4, column 2",
  "Empty cell of color Vibrant Coral, row 4, column 3",
  "Empty cell of color Lime Yellow, row 4, column 4",
  "Empty cell of color Lime Yellow, row 4, column 5",
  "Empty cell of color Lime Yellow, row 4, column 6",
  "Empty cell of color Lime Yellow, row 4, column 7",
  "Empty cell of color Warm Beige, row 4, column 8",
  "Empty cell of color Light Gray, row 4, column 9",
  "Empty cell of color Light Gray, row 4, column 10",
  "Empty cell of color Vibrant Coral, row 5, column 1",
  "Empty cell of color Vibrant Coral, row 5, column 2",
  "Empty cell of color Soft Blue, row 5, column 3",
  "Empty cell of color Lime Yellow, row 5, column 4",
  "Empty cell of color Lime Yellow, row 5, column 5",
  "Empty cell of color Lime Yellow, row 5, column 6",
  "Empty cell of color Lime Yellow, row 5, column 7",
  "Empty cell of color Warm Beige, row 5, column 8",
  "Empty cell of color Warm Beige, row 5, column 9",
  "Empty cell of color Light Gray, row 5, column 10",
  "Empty cell of color Soft Blue, row 6, column 1",
  "Empty cell of color Soft Blue, row 6, column 2",
  "Empty cell of color Soft Blue, row 6, column 3",
  "Empty cell of color Soft Blue, row 6, column 4",
  "Empty cell of color Lime Yellow, row 6, column 5",
  "Empty cell of color Lime Yellow, row 6, column 6",
  "Empty cell of color Peach Orange, row 6, column 7",
  "Empty cell of color Peach Orange, row 6, column 8",
  "Empty cell of color Warm Beige, row 6, column 9",
  "Empty cell of color Peach Orange, row 6, column 10",
  "Empty cell of color Soft Blue, row 7, column 1",
  "Empty cell of color Soft Blue, row 7, column 2",
  "Empty cell of color Soft Blue, row 7, column 3",
  "Empty cell of color Soft Blue, row 7, column 4",
  "Empty cell of color Lime Yellow, row 7, column 5",
  "Empty cell of color Lime Yellow, row 7, column 6",
  "Empty cell of color Peach Orange, row 7, column 7",
  "Empty cell of color Peach Orange, row 7, column 8",
  "Empty cell of color Peach Orange, row 7, column 9",
  "Empty cell of color Peach Orange, row 7, column 10",
  "Empty cell of color Soft Blue, row 8, column 1",
  "Empty cell of color Muted Teal, row 8, column 2",
  "Empty cell of color Soft Blue, row 8, column 3",
  "Empty cell of color Muted Teal, row 8, column 4",
  "Empty cell of color Lime Yellow, row 8, column 5",
  "Empty cell of color Lime Yellow, row 8, column 6",
  "Empty cell of color Muted Teal, row 8, column 7",
  "Empty cell of color Peach Orange, row 8, column 8",
  "Empty cell of color Muted Teal, row 8, column 9",
  "Empty cell of color Peach Orange, row 8, column 10",
  "Empty cell of color Soft Blue, row 9, column 1",
  "Empty cell of color Muted Teal, row 9, column 2",
  "Empty cell of color Muted Teal, row 9, column 3",
  "Empty cell of color Muted Teal, row 9, column 4",
  "Empty cell of color Lime Yellow, row 9, column 5",
  "Empty cell of color Lime Yellow, row 9, column 6",
  "Empty cell of color Muted Teal, row 9, column 7",
  "Empty cell of color Muted Teal, row 9, column 8",
  "Empty cell of color Muted Teal, row 9, column 9",
  "Empty cell of color Peach Orange, row 9, column 10",
  "Empty cell of color Soft Blue, row 10, column 1",
  "Empty cell of color Soft Blue, row 10, column 2",
  "Empty cell of color Muted Teal, row 10, column 3",
  "Empty cell of color Muted Teal, row 10, column 4",
  "Empty cell of color Muted Teal, row 10, column 5",
  "Empty cell of color Muted Teal, row 10, column 6",
  "Empty cell of color Muted Teal, row 10, column 7",
  "Empty cell of color Muted Teal, row 10, column 8",
  "Empty cell of color Peach Orange, row 10, column 9",
  "Empty cell of color Peach Orange, row 10, column 10",
];

export const squirtlespawn = [
  "Empty cell of color Lavender, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Peach Orange, row 1, column 3",
  "Queen of color Peach Orange, row 1, column 4",
  "Empty cell of color Peach Orange, row 1, column 5",
  "Empty cell of color Peach Orange, row 1, column 6",
  "Empty cell of color Soft Blue, row 1, column 7",
  "Empty cell of color Pastel Green, row 1, column 8",
  "Empty cell of color Lavender, row 2, column 1",
  "Empty cell of color Lavender, row 2, column 2",
  "Empty cell of color Lavender, row 2, column 3",
  "Empty cell of color Peach Orange, row 2, column 4",
  "Empty cell of color Peach Orange, row 2, column 5",
  "Empty cell of color Pastel Green, row 2, column 6",
  "Queen of color Soft Blue, row 2, column 7",
  "Empty cell of color Pastel Green, row 2, column 8",
  "Empty cell of color Lavender, row 3, column 1",
  "Empty cell of color Lavender, row 3, column 2",
  "Empty cell of color Light Gray, row 3, column 3",
  "Empty cell of color Light Gray, row 3, column 4",
  "Empty cell of color Pastel Green, row 3, column 5",
  "Empty cell of color Pastel Green, row 3, column 6",
  "Empty cell of color Pastel Green, row 3, column 7",
  "Empty cell of color Pastel Green, row 3, column 8",
  "Empty cell of color Lavender, row 4, column 1",
  "Empty cell of color Vibrant Coral, row 4, column 2",
  "Empty cell of color Light Gray, row 4, column 3",
  "Empty cell of color Pastel Green, row 4, column 4",
  "Empty cell of color Pastel Green, row 4, column 5",
  "Empty cell of color Lime Yellow, row 4, column 6",
  "Empty cell of color Lime Yellow, row 4, column 7",
  "Empty cell of color Lime Yellow, row 4, column 8",
  "Empty cell of color Lavender, row 5, column 1",
  "Empty cell of color Vibrant Coral, row 5, column 2",
  "Empty cell of color Vibrant Coral, row 5, column 3",
  "Empty cell of color Warm Beige, row 5, column 4",
  "Empty cell of color Warm Beige, row 5, column 5",
  "Empty cell of color Lime Yellow, row 5, column 6",
  "Empty cell of color Lime Yellow, row 5, column 7",
  "Empty cell of color Lime Yellow, row 5, column 8",
  "Empty cell of color Lavender, row 6, column 1",
  "Empty cell of color Vibrant Coral, row 6, column 2",
  "Empty cell of color Warm Beige, row 6, column 3",
  "Empty cell of color Warm Beige, row 6, column 4",
  "Empty cell of color Warm Beige, row 6, column 5",
  "Empty cell of color Warm Beige, row 6, column 6",
  "Empty cell of color Lime Yellow, row 6, column 7",
  "Empty cell of color Lime Yellow, row 6, column 8",
  "Empty cell of color Lavender, row 7, column 1",
  "Empty cell of color Warm Beige, row 7, column 2",
  "Empty cell of color Warm Beige, row 7, column 3",
  "Empty cell of color Warm Beige, row 7, column 4",
  "Empty cell of color Warm Beige, row 7, column 5",
  "Empty cell of color Warm Beige, row 7, column 6",
  "Empty cell of color Warm Beige, row 7, column 7",
  "Empty cell of color Lime Yellow, row 7, column 8",
  "Empty cell of color Warm Beige, row 8, column 1",
  "Empty cell of color Warm Beige, row 8, column 2",
  "Empty cell of color Warm Beige, row 8, column 3",
  "Empty cell of color Warm Beige, row 8, column 4",
  "Empty cell of color Warm Beige, row 8, column 5",
  "Empty cell of color Warm Beige, row 8, column 6",
  "Empty cell of color Warm Beige, row 8, column 7",
  "Empty cell of color Warm Beige, row 8, column 8",
];

export const holyGrail = [
  "Empty cell of color Lavender, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Rose Pink, row 1, column 3",
  "Empty cell of color Rose Pink, row 1, column 4",
  "Empty cell of color Soft Blue, row 1, column 5",
  "Empty cell of color Soft Blue, row 1, column 6",
  "Empty cell of color Soft Blue, row 1, column 7",
  "Queen of color Soft Blue, row 1, column 8",
  "Empty cell of color Soft Blue, row 1, column 9",
  "Empty cell of color Soft Blue, row 1, column 10",

  "Empty cell of color Lavender, row 2, column 1",
  "Empty cell of color Lavender, row 2, column 2",
  "Empty cell of color Lavender, row 2, column 3",
  "Empty cell of color Rose Pink, row 2, column 4",
  "Queen of color Rose Pink, row 2, column 5",
  "Empty cell of color Pastel Green, row 2, column 6",
  "Empty cell of color Soft Blue, row 2, column 7",
  "Empty cell of color Soft Blue, row 2, column 8",
  "Empty cell of color Soft Blue, row 2, column 9",
  "Empty cell of color Soft Blue, row 2, column 10",

  "Empty cell of color Light Gray, row 3, column 1",
  "Empty cell of color Lavender, row 3, column 2",
  "Empty cell of color Lavender, row 3, column 3",
  "Empty cell of color Lavender, row 3, column 4",
  "Empty cell of color Rose Pink, row 3, column 5",
  "Empty cell of color Pastel Green, row 3, column 6",
  "Empty cell of color Pastel Green, row 3, column 7",
  "Empty cell of color Soft Blue, row 3, column 8",
  "Empty cell of color Soft Blue, row 3, column 9",
  "Empty cell of color Warm Beige, row 3, column 10",

  "Empty cell of color Light Gray, row 4, column 1",
  "Empty cell of color Light Gray, row 4, column 2",
  "Empty cell of color Lavender, row 4, column 3",
  "Empty cell of color Lavender, row 4, column 4",
  "Empty cell of color Lavender, row 4, column 5",
  "Empty cell of color Pastel Green, row 4, column 6",
  "Empty cell of color Soft Blue, row 4, column 7",
  "Empty cell of color Soft Blue, row 4, column 8",
  "Empty cell of color Warm Beige, row 4, column 9",
  "Empty cell of color Warm Beige, row 4, column 10",

  "Empty cell of color Soft Blue, row 5, column 1",
  "Empty cell of color Lime Yellow, row 5, column 2",
  "Empty cell of color Lime Yellow, row 5, column 3",
  "Empty cell of color Lavender, row 5, column 4",
  "Empty cell of color Soft Blue, row 5, column 5",
  "Empty cell of color Soft Blue, row 5, column 6",
  "Empty cell of color Soft Blue, row 5, column 7",
  "Empty cell of color Warm Beige, row 5, column 8",
  "Empty cell of color Warm Beige, row 5, column 9",
  "Empty cell of color Warm Beige, row 5, column 10",

  "Empty cell of color Soft Blue, row 6, column 1",
  "Empty cell of color Lime Yellow, row 6, column 2",
  "Empty cell of color Lime Yellow, row 6, column 3",
  "Empty cell of color Lime Yellow, row 6, column 4",
  "Empty cell of color Soft Blue, row 6, column 5",
  "Empty cell of color Soft Blue, row 6, column 6",
  "Empty cell of color Vibrant Coral, row 6, column 7",
  "Empty cell of color Vibrant Coral, row 6, column 8",
  "Empty cell of color Warm Beige, row 6, column 9",
  "Empty cell of color Warm Beige, row 6, column 10",

  "Empty cell of color Soft Blue, row 7, column 1",
  "Empty cell of color Soft Blue, row 7, column 2",
  "Empty cell of color Lime Yellow, row 7, column 3",
  "Empty cell of color Soft Blue, row 7, column 4",
  "Empty cell of color Soft Blue, row 7, column 5",
  "Empty cell of color Vibrant Coral, row 7, column 6",
  "Empty cell of color Vibrant Coral, row 7, column 7",
  "Empty cell of color Vibrant Coral, row 7, column 8",
  "Empty cell of color Warm Beige, row 7, column 9",
  "Empty cell of color Warm Beige, row 7, column 10",

  "Empty cell of color Soft Blue, row 8, column 1",
  "Empty cell of color Soft Blue, row 8, column 2",
  "Empty cell of color Soft Blue, row 8, column 3",
  "Empty cell of color Soft Blue, row 8, column 4",
  "Empty cell of color Peach Orange, row 8, column 5",
  "Empty cell of color Vibrant Coral, row 8, column 6",
  "Empty cell of color Vibrant Coral, row 8, column 7",
  "Empty cell of color Vibrant Coral, row 8, column 8",
  "Empty cell of color Vibrant Coral, row 8, column 9",
  "Empty cell of color Vibrant Coral, row 8, column 10",

  "Empty cell of color Soft Blue, row 9, column 1",
  "Empty cell of color Soft Blue, row 9, column 2",
  "Empty cell of color Soft Blue, row 9, column 3",
  "Empty cell of color Muted Teal, row 9, column 4",
  "Empty cell of color Peach Orange, row 9, column 5",
  "Empty cell of color Peach Orange, row 9, column 6",
  "Empty cell of color Peach Orange, row 9, column 7",
  "Empty cell of color Vibrant Coral, row 9, column 8",
  "Empty cell of color Vibrant Coral, row 9, column 9",
  "Empty cell of color Vibrant Coral, row 9, column 10",

  "Empty cell of color Soft Blue, row 10, column 1",
  "Empty cell of color Soft Blue, row 10, column 2",
  "Empty cell of color Muted Teal, row 10, column 3",
  "Empty cell of color Muted Teal, row 10, column 4",
  "Empty cell of color Muted Teal, row 10, column 5",
  "Empty cell of color Peach Orange, row 10, column 6",
  "Empty cell of color Peach Orange, row 10, column 7",
  "Empty cell of color Vibrant Coral, row 10, column 8",
  "Empty cell of color Vibrant Coral, row 10, column 9",
  "Empty cell of color Vibrant Coral, row 10, column 10",
];

export const luBdayNight = [
  "Queen of color Lavender, row 1, column 1",
  "Empty cell of color Lavender, row 1, column 2",
  "Empty cell of color Lavender, row 1, column 3",
  "Empty cell of color Bright Cyan, row 1, column 4",
  "Empty cell of color Bright Cyan, row 1, column 5",
  "Empty cell of color Bright Cyan, row 1, column 6",
  "Empty cell of color Bright Cyan, row 1, column 7",
  "Empty cell of color Soft Blue, row 1, column 8",
  "Empty cell of color Soft Blue, row 1, column 9",
  "Empty cell of color Soft Blue, row 1, column 10",
  "Empty cell of color Bright Cyan, row 1, column 11",
  "Empty cell of color Bright Cyan, row 2, column 1",
  "Empty cell of color Lavender, row 2, column 2",
  "Queen of color Vibrant Coral, row 2, column 3",
  "Empty cell of color Vibrant Coral, row 2, column 4",
  "Empty cell of color Vibrant Coral, row 2, column 5",
  "Empty cell of color Bright Cyan, row 2, column 6",
  "Empty cell of color Bright Cyan, row 2, column 7",
  "Empty cell of color Bright Cyan, row 2, column 8",
  "Empty cell of color Soft Blue, row 2, column 9",
  "Empty cell of color Bright Cyan, row 2, column 10",
  "Empty cell of color Bright Cyan, row 2, column 11",
  "Empty cell of color Bright Cyan, row 3, column 1",
  "Empty cell of color Lavender, row 3, column 2",
  "Empty cell of color Light Gray, row 3, column 3",
  "Empty cell of color Vibrant Coral, row 3, column 4",
  "Empty cell of color Pastel Green, row 3, column 5",
  "Empty cell of color Pastel Green, row 3, column 6",
  "Empty cell of color Pastel Green, row 3, column 7",
  "Empty cell of color Bright Cyan, row 3, column 8",
  "Empty cell of color Soft Blue, row 3, column 9",
  "Empty cell of color Bright Cyan, row 3, column 10",
  "Empty cell of color Bright Cyan, row 3, column 11",
  "Empty cell of color Bright Cyan, row 4, column 1",
  "Empty cell of color Bright Cyan, row 4, column 2",
  "Empty cell of color Light Gray, row 4, column 3",
  "Empty cell of color Vibrant Coral, row 4, column 4",
  "Empty cell of color Bright Cyan, row 4, column 5",
  "Empty cell of color Pastel Green, row 4, column 6",
  "Empty cell of color Lime Yellow, row 4, column 7",
  "Empty cell of color Bright Cyan, row 4, column 8",
  "Empty cell of color Bright Cyan, row 4, column 9",
  "Empty cell of color Bright Cyan, row 4, column 10",
  "Empty cell of color Bright Cyan, row 4, column 11",
  "Empty cell of color Bright Cyan, row 5, column 1",
  "Empty cell of color Light Gray, row 5, column 2",
  "Empty cell of color Light Gray, row 5, column 3",
  "Empty cell of color Light Gray, row 5, column 4",
  "Empty cell of color Bright Cyan, row 5, column 5",
  "Empty cell of color Pastel Green, row 5, column 6",
  "Empty cell of color Lime Yellow, row 5, column 7",
  "Empty cell of color Lime Yellow, row 5, column 8",
  "Empty cell of color Lime Yellow, row 5, column 9",
  "Empty cell of color Warm Beige, row 5, column 10",
  "Empty cell of color Bright Cyan, row 5, column 11",
  "Empty cell of color Bright Cyan, row 6, column 1",
  "Empty cell of color Bright Cyan, row 6, column 2",
  "Empty cell of color Bright Cyan, row 6, column 3",
  "Empty cell of color Bright Cyan, row 6, column 4",
  "Empty cell of color Bright Cyan, row 6, column 5",
  "Empty cell of color Bright Cyan, row 6, column 6",
  "Empty cell of color Lime Yellow, row 6, column 7",
  "Empty cell of color Warm Beige, row 6, column 8",
  "Empty cell of color Warm Beige, row 6, column 9",
  "Empty cell of color Warm Beige, row 6, column 10",
  "Empty cell of color Bright Cyan, row 6, column 11",
  "Empty cell of color Bright Cyan, row 7, column 1",
  "Empty cell of color Bright Cyan, row 7, column 2",
  "Empty cell of color Bright Cyan, row 7, column 3",
  "Empty cell of color Bright Cyan, row 7, column 4",
  "Empty cell of color Bright Cyan, row 7, column 5",
  "Empty cell of color Bright Cyan, row 7, column 6",
  "Empty cell of color Bright Cyan, row 7, column 7",
  "Empty cell of color Bright Cyan, row 7, column 8",
  "Empty cell of color Bright Cyan, row 7, column 9",
  "Empty cell of color Warm Beige, row 7, column 10",
  "Empty cell of color Bright Cyan, row 7, column 11",
  "Empty cell of color Bright Cyan, row 8, column 1",
  "Empty cell of color Bright Cyan, row 8, column 2",
  "Empty cell of color Bright Cyan, row 8, column 3",
  "Empty cell of color Bright Cyan, row 8, column 4",
  "Empty cell of color Rose Pink, row 8, column 5",
  "Empty cell of color Bright Cyan, row 8, column 6",
  "Empty cell of color Rose Pink, row 8, column 7",
  "Empty cell of color Bright Cyan, row 8, column 8",
  "Empty cell of color Bright Cyan, row 8, column 9",
  "Empty cell of color Bright Cyan, row 8, column 10",
  "Empty cell of color Bright Cyan, row 8, column 11",
  "Empty cell of color Bright Cyan, row 9, column 1",
  "Empty cell of color Bright Cyan, row 9, column 2",
  "Empty cell of color Bright Cyan, row 9, column 3",
  "Empty cell of color Muted Teal, row 9, column 4",
  "Empty cell of color Rose Pink, row 9, column 5",
  "Empty cell of color Rose Pink, row 9, column 6",
  "Empty cell of color Rose Pink, row 9, column 7",
  "Empty cell of color Bright Cyan, row 9, column 8",
  "Empty cell of color Bright Cyan, row 9, column 9",
  "Empty cell of color Peach Orange, row 9, column 10",
  "Empty cell of color Bright Cyan, row 9, column 11",
  "Empty cell of color Bright Cyan, row 10, column 1",
  "Empty cell of color Bright Cyan, row 10, column 2",
  "Empty cell of color Bright Cyan, row 10, column 3",
  "Empty cell of color Muted Teal, row 10, column 4",
  "Empty cell of color Rose Pink, row 10, column 5",
  "Empty cell of color Bright Cyan, row 10, column 6",
  "Empty cell of color Rose Pink, row 10, column 7",
  "Empty cell of color Bright Cyan, row 10, column 8",
  "Empty cell of color Bright Cyan, row 10, column 9",
  "Empty cell of color Peach Orange, row 10, column 10",
  "Empty cell of color Bright Cyan, row 10, column 11",
  "Empty cell of color Bright Cyan, row 11, column 1",
  "Empty cell of color Bright Cyan, row 11, column 2",
  "Empty cell of color Muted Teal, row 11, column 3",
  "Empty cell of color Muted Teal, row 11, column 4",
  "Empty cell of color Muted Teal, row 11, column 5",
  "Empty cell of color Bright Cyan, row 11, column 6",
  "Empty cell of color Bright Cyan, row 11, column 7",
  "Empty cell of color Bright Cyan, row 11, column 8",
  "Empty cell of color Peach Orange, row 11, column 9",
  "Empty cell of color Peach Orange, row 11, column 10",
  "Empty cell of color Peach Orange, row 11, column 11",
];

export const piDay = [
  'Empty cell of color Vibrant Coral, row 1, column 1',
    'Empty cell of color Vibrant Coral, row 1, column 2',
    'Empty cell of color Vibrant Coral, row 1, column 3',
    'Empty cell of color Vibrant Coral, row 1, column 4',
    'Queen of color Vibrant Coral, row 1, column 5',
    'Empty cell of color Vibrant Coral, row 1, column 6',
    'Empty cell of color Vibrant Coral, row 1, column 7',
    'Empty cell of color Vibrant Coral, row 1, column 8',
    'Empty cell of color Vibrant Coral, row 1, column 9',
    'Empty cell of color Vibrant Coral, row 2, column 1',
    'Empty cell of color Vibrant Coral, row 2, column 2',
    'Queen of color Peach Orange, row 2, column 3',
    'Empty cell of color Peach Orange, row 2, column 4',
    'Empty cell of color Vibrant Coral, row 2, column 5',
    'Empty cell of color Vibrant Coral, row 2, column 6',
    'Empty cell of color Vibrant Coral, row 2, column 7',
    'Empty cell of color Vibrant Coral, row 2, column 8',
    'Empty cell of color Vibrant Coral, row 2, column 9',
    'Empty cell of color Lime Yellow, row 3, column 1',
    'Empty cell of color Lime Yellow, row 3, column 2',
    'Empty cell of color Lime Yellow, row 3, column 3',
    'Empty cell of color Peach Orange, row 3, column 4',
    'Empty cell of color Soft Blue, row 3, column 5',
    'Empty cell of color Soft Blue, row 3, column 6',
    'Empty cell of color Lavender, row 3, column 7',
    'Empty cell of color Vibrant Coral, row 3, column 8',
    'Empty cell of color Lavender, row 3, column 9',
    'Empty cell of color Light Gray, row 4, column 1',
    'Empty cell of color Light Gray, row 4, column 2',
    'Empty cell of color Lime Yellow, row 4, column 3',
    'Empty cell of color Peach Orange, row 4, column 4',
    'Empty cell of color Peach Orange, row 4, column 5',
    'Empty cell of color Soft Blue, row 4, column 6',
    'Empty cell of color Lavender, row 4, column 7',
    'Empty cell of color Vibrant Coral, row 4, column 8',
    'Empty cell of color Lavender, row 4, column 9',
    'Empty cell of color Light Gray, row 5, column 1',
    'Empty cell of color Lime Yellow, row 5, column 2',
    'Empty cell of color Lime Yellow, row 5, column 3',
    'Empty cell of color Peach Orange, row 5, column 4',
    'Empty cell of color Peach Orange, row 5, column 5',
    'Empty cell of color Soft Blue, row 5, column 6',
    'Empty cell of color Lavender, row 5, column 7',
    'Empty cell of color Lavender, row 5, column 8',
    'Empty cell of color Lavender, row 5, column 9',
    'Empty cell of color Light Gray, row 6, column 1',
    'Empty cell of color Light Gray, row 6, column 2',
    'Empty cell of color Lime Yellow, row 6, column 3',
    'Empty cell of color Peach Orange, row 6, column 4',
    'Empty cell of color Peach Orange, row 6, column 5',
    'Empty cell of color Soft Blue, row 6, column 6',
    'Empty cell of color Rose Pink, row 6, column 7',
    'Empty cell of color Rose Pink, row 6, column 8',
    'Empty cell of color Lavender, row 6, column 9',
    'Empty cell of color Lime Yellow, row 7, column 1',
    'Empty cell of color Lime Yellow, row 7, column 2',
    'Empty cell of color Lime Yellow, row 7, column 3',
    'Empty cell of color Warm Beige, row 7, column 4',
    'Empty cell of color Soft Blue, row 7, column 5',
    'Empty cell of color Soft Blue, row 7, column 6',
    'Empty cell of color Soft Blue, row 7, column 7',
    'Empty cell of color Rose Pink, row 7, column 8',
    'Empty cell of color Lavender, row 7, column 9',
    'Empty cell of color Rose Pink, row 8, column 1',
    'Empty cell of color Rose Pink, row 8, column 2',
    'Empty cell of color Rose Pink, row 8, column 3',
    'Empty cell of color Rose Pink, row 8, column 4',
    'Empty cell of color Rose Pink, row 8, column 5',
    'Empty cell of color Rose Pink, row 8, column 6',
    'Empty cell of color Rose Pink, row 8, column 7',
    'Empty cell of color Rose Pink, row 8, column 8',
    'Empty cell of color Rose Pink, row 8, column 9',
    'Empty cell of color Rose Pink, row 9, column 1',
    'Empty cell of color Rose Pink, row 9, column 2',
    'Empty cell of color Rose Pink, row 9, column 3',
    'Empty cell of color Rose Pink, row 9, column 4',
    'Empty cell of color Rose Pink, row 9, column 5',
    'Empty cell of color Rose Pink, row 9, column 6',
    'Empty cell of color Rose Pink, row 9, column 7',
    'Empty cell of color Rose Pink, row 9, column 8',
    'Empty cell of color Pastel Green, row 9, column 9'
]

export const piSymbol = [
  'Empty cell of color Vibrant Coral, row 1, column 1',
    'Empty cell of color Vibrant Coral, row 1, column 2',
    'Empty cell of color Vibrant Coral, row 1, column 3',
    'Queen of color Vibrant Coral, row 1, column 4',
    'Empty cell of color Vibrant Coral, row 1, column 5',
    'Empty cell of color Vibrant Coral, row 1, column 6',
    'Empty cell of color Vibrant Coral, row 1, column 7',
    'Empty cell of color Peach Orange, row 1, column 8',
    'Empty cell of color Peach Orange, row 1, column 9',
    'Empty cell of color Vibrant Coral, row 2, column 1',
    'Empty cell of color Soft Blue, row 2, column 2',
    'Empty cell of color Soft Blue, row 2, column 3',
    'Empty cell of color Soft Blue, row 2, column 4',
    'Empty cell of color Soft Blue, row 2, column 5',
    'Queen of color Soft Blue, row 2, column 6',
    'Empty cell of color Soft Blue, row 2, column 7',
    'Empty cell of color Soft Blue, row 2, column 8',
    'Empty cell of color Peach Orange, row 2, column 9',
    'Empty cell of color Vibrant Coral, row 3, column 1',
    'Empty cell of color Soft Blue, row 3, column 2',
    'Empty cell of color Rose Pink, row 3, column 3',
    'Empty cell of color Rose Pink, row 3, column 4',
    'Empty cell of color Rose Pink, row 3, column 5',
    'Empty cell of color Rose Pink, row 3, column 6',
    'Empty cell of color Rose Pink, row 3, column 7',
    'Empty cell of color Soft Blue, row 3, column 8',
    'Empty cell of color Peach Orange, row 3, column 9',
    'Empty cell of color Vibrant Coral, row 4, column 1',
    'Empty cell of color Soft Blue, row 4, column 2',
    'Empty cell of color Soft Blue, row 4, column 3',
    'Empty cell of color Rose Pink, row 4, column 4',
    'Empty cell of color Light Gray, row 4, column 5',
    'Empty cell of color Rose Pink, row 4, column 6',
    'Empty cell of color Soft Blue, row 4, column 7',
    'Empty cell of color Soft Blue, row 4, column 8',
    'Empty cell of color Peach Orange, row 4, column 9',
    'Empty cell of color Vibrant Coral, row 5, column 1',
    'Empty cell of color Vibrant Coral, row 5, column 2',
    'Empty cell of color Soft Blue, row 5, column 3',
    'Empty cell of color Rose Pink, row 5, column 4',
    'Empty cell of color Light Gray, row 5, column 5',
    'Empty cell of color Rose Pink, row 5, column 6',
    'Empty cell of color Soft Blue, row 5, column 7',
    'Empty cell of color Peach Orange, row 5, column 8',
    'Empty cell of color Peach Orange, row 5, column 9',
    'Empty cell of color Lavender, row 6, column 1',
    'Empty cell of color Vibrant Coral, row 6, column 2',
    'Empty cell of color Soft Blue, row 6, column 3',
    'Empty cell of color Rose Pink, row 6, column 4',
    'Empty cell of color Light Gray, row 6, column 5',
    'Empty cell of color Rose Pink, row 6, column 6',
    'Empty cell of color Soft Blue, row 6, column 7',
    'Empty cell of color Lime Yellow, row 6, column 8',
    'Empty cell of color Lime Yellow, row 6, column 9',
    'Empty cell of color Lavender, row 7, column 1',
    'Empty cell of color Lavender, row 7, column 2',
    'Empty cell of color Soft Blue, row 7, column 3',
    'Empty cell of color Rose Pink, row 7, column 4',
    'Empty cell of color Light Gray, row 7, column 5',
    'Empty cell of color Rose Pink, row 7, column 6',
    'Empty cell of color Soft Blue, row 7, column 7',
    'Empty cell of color Warm Beige, row 7, column 8',
    'Empty cell of color Lime Yellow, row 7, column 9',
    'Empty cell of color Lavender, row 8, column 1',
    'Empty cell of color Pastel Green, row 8, column 2',
    'Empty cell of color Soft Blue, row 8, column 3',
    'Empty cell of color Soft Blue, row 8, column 4',
    'Empty cell of color Soft Blue, row 8, column 5',
    'Empty cell of color Soft Blue, row 8, column 6',
    'Empty cell of color Soft Blue, row 8, column 7',
    'Empty cell of color Warm Beige, row 8, column 8',
    'Empty cell of color Lime Yellow, row 8, column 9',
    'Empty cell of color Lavender, row 9, column 1',
    'Empty cell of color Pastel Green, row 9, column 2',
    'Empty cell of color Pastel Green, row 9, column 3',
    'Empty cell of color Pastel Green, row 9, column 4',
    'Empty cell of color Pastel Green, row 9, column 5',
    'Empty cell of color Pastel Green, row 9, column 6',
    'Empty cell of color Warm Beige, row 9, column 7',
    'Empty cell of color Warm Beige, row 9, column 8',
    'Empty cell of color Warm Beige, row 9, column 9'
]

export const easyOneIShouldHaveGot = [
  'Queen of color Lavender, row 1, column 1',
    'Empty cell of color Lavender, row 1, column 2',
    'Empty cell of color Lavender, row 1, column 3',
    'Empty cell of color Lavender, row 1, column 4',
    'Empty cell of color Lavender, row 1, column 5',
    'Empty cell of color Lavender, row 1, column 6',
    'Empty cell of color Peach Orange, row 1, column 7',
    'Empty cell of color Peach Orange, row 1, column 8',
    'Empty cell of color Lavender, row 2, column 1',
    'Empty cell of color Lavender, row 2, column 2',
    'Empty cell of color Lavender, row 2, column 3',
    'Queen of color Soft Blue, row 2, column 4',
    'Empty cell of color Pastel Green, row 2, column 5',
    'Empty cell of color Peach Orange, row 2, column 6',
    'Empty cell of color Peach Orange, row 2, column 7',
    'Empty cell of color Peach Orange, row 2, column 8',
    'Empty cell of color Lavender, row 3, column 1',
    'Empty cell of color Lavender, row 3, column 2',
    'Empty cell of color Soft Blue, row 3, column 3',
    'Empty cell of color Soft Blue, row 3, column 4',
    'Empty cell of color Pastel Green, row 3, column 5',
    'Empty cell of color Pastel Green, row 3, column 6',
    'Empty cell of color Peach Orange, row 3, column 7',
    'Empty cell of color Peach Orange, row 3, column 8',
    'Empty cell of color Lavender, row 4, column 1',
    'Empty cell of color Light Gray, row 4, column 2',
    'Empty cell of color Light Gray, row 4, column 3',
    'Empty cell of color Light Gray, row 4, column 4',
    'Empty cell of color Pastel Green, row 4, column 5',
    'Empty cell of color Pastel Green, row 4, column 6',
    'Empty cell of color Pastel Green, row 4, column 7',
    'Empty cell of color Peach Orange, row 4, column 8',
    'Empty cell of color Lavender, row 5, column 1',
    'Empty cell of color Vibrant Coral, row 5, column 2',
    'Empty cell of color Vibrant Coral, row 5, column 3',
    'Empty cell of color Vibrant Coral, row 5, column 4',
    'Empty cell of color Lime Yellow, row 5, column 5',
    'Empty cell of color Lime Yellow, row 5, column 6',
    'Empty cell of color Lime Yellow, row 5, column 7',
    'Empty cell of color Peach Orange, row 5, column 8',
    'Empty cell of color Lavender, row 6, column 1',
    'Empty cell of color Warm Beige, row 6, column 2',
    'Empty cell of color Vibrant Coral, row 6, column 3',
    'Empty cell of color Vibrant Coral, row 6, column 4',
    'Empty cell of color Lime Yellow, row 6, column 5',
    'Empty cell of color Lime Yellow, row 6, column 6',
    'Empty cell of color Warm Beige, row 6, column 7',
    'Empty cell of color Peach Orange, row 6, column 8',
    'Empty cell of color Warm Beige, row 7, column 1',
    'Empty cell of color Warm Beige, row 7, column 2',
    'Empty cell of color Warm Beige, row 7, column 3',
    'Empty cell of color Vibrant Coral, row 7, column 4',
    'Empty cell of color Lime Yellow, row 7, column 5',
    'Empty cell of color Warm Beige, row 7, column 6',
    'Empty cell of color Warm Beige, row 7, column 7',
    'Empty cell of color Peach Orange, row 7, column 8',
    'Empty cell of color Warm Beige, row 8, column 1',
    'Empty cell of color Warm Beige, row 8, column 2',
    'Empty cell of color Warm Beige, row 8, column 3',
    'Empty cell of color Warm Beige, row 8, column 4',
    'Empty cell of color Warm Beige, row 8, column 5',
    'Empty cell of color Warm Beige, row 8, column 6',
    'Empty cell of color Peach Orange, row 8, column 7',
    'Empty cell of color Peach Orange, row 8, column 8'
]

export const miamiOpen = [
  'Empty cell of color Vibrant Coral, row 1, column 1',
    'Empty cell of color Vibrant Coral, row 1, column 2',
    'Queen of color Lavender, row 1, column 3',
    'Empty cell of color Lavender, row 1, column 4',
    'Empty cell of color Warm Beige, row 1, column 5',
    'Empty cell of color Warm Beige, row 1, column 6',
    'Empty cell of color Warm Beige, row 1, column 7',
    'Empty cell of color Warm Beige, row 1, column 8',
    'Empty cell of color Warm Beige, row 1, column 9',
    'Empty cell of color Vibrant Coral, row 2, column 1',
    'Empty cell of color Vibrant Coral, row 2, column 2',
    'Empty cell of color Vibrant Coral, row 2, column 3',
    'Empty cell of color Lavender, row 2, column 4',
    'Empty cell of color Warm Beige, row 2, column 5',
    'Empty cell of color Peach Orange, row 2, column 6',
    'Empty cell of color Warm Beige, row 2, column 7',
    'Empty cell of color Warm Beige, row 2, column 8',
    'Queen of color Warm Beige, row 2, column 9',
    'Empty cell of color Rose Pink, row 3, column 1',
    'Empty cell of color Vibrant Coral, row 3, column 2',
    'Empty cell of color Vibrant Coral, row 3, column 3',
    'Empty cell of color Lavender, row 3, column 4',
    'Empty cell of color Lavender, row 3, column 5',
    'Empty cell of color Peach Orange, row 3, column 6',
    'Empty cell of color Soft Blue, row 3, column 7',
    'Empty cell of color Soft Blue, row 3, column 8',
    'Empty cell of color Warm Beige, row 3, column 9',
    'Empty cell of color Rose Pink, row 4, column 1',
    'Empty cell of color Rose Pink, row 4, column 2',
    'Empty cell of color Vibrant Coral, row 4, column 3',
    'Empty cell of color Vibrant Coral, row 4, column 4',
    'Empty cell of color Vibrant Coral, row 4, column 5',
    'Empty cell of color Peach Orange, row 4, column 6',
    'Empty cell of color Soft Blue, row 4, column 7',
    'Empty cell of color Soft Blue, row 4, column 8',
    'Empty cell of color Warm Beige, row 4, column 9',
    'Empty cell of color Rose Pink, row 5, column 1',
    'Empty cell of color Pastel Green, row 5, column 2',
    'Empty cell of color Pastel Green, row 5, column 3',
    'Empty cell of color Vibrant Coral, row 5, column 4',
    'Empty cell of color Vibrant Coral, row 5, column 5',
    'Empty cell of color Vibrant Coral, row 5, column 6',
    'Empty cell of color Soft Blue, row 5, column 7',
    'Empty cell of color Vibrant Coral, row 5, column 8',
    'Empty cell of color Vibrant Coral, row 5, column 9',
    'Empty cell of color Rose Pink, row 6, column 1',
    'Empty cell of color Rose Pink, row 6, column 2',
    'Empty cell of color Pastel Green, row 6, column 3',
    'Empty cell of color Vibrant Coral, row 6, column 4',
    'Empty cell of color Light Gray, row 6, column 5',
    'Empty cell of color Vibrant Coral, row 6, column 6',
    'Empty cell of color Vibrant Coral, row 6, column 7',
    'Empty cell of color Vibrant Coral, row 6, column 8',
    'Empty cell of color Vibrant Coral, row 6, column 9',
    'Empty cell of color Rose Pink, row 7, column 1',
    'Empty cell of color Rose Pink, row 7, column 2',
    'Empty cell of color Pastel Green, row 7, column 3',
    'Empty cell of color Pastel Green, row 7, column 4',
    'Empty cell of color Light Gray, row 7, column 5',
    'Empty cell of color Lime Yellow, row 7, column 6',
    'Empty cell of color Lime Yellow, row 7, column 7',
    'Empty cell of color Vibrant Coral, row 7, column 8',
    'Empty cell of color Vibrant Coral, row 7, column 9',
    'Empty cell of color Rose Pink, row 8, column 1',
    'Empty cell of color Rose Pink, row 8, column 2',
    'Empty cell of color Rose Pink, row 8, column 3',
    'Empty cell of color Rose Pink, row 8, column 4',
    'Empty cell of color Light Gray, row 8, column 5',
    'Empty cell of color Lime Yellow, row 8, column 6',
    'Empty cell of color Lime Yellow, row 8, column 7',
    'Empty cell of color Vibrant Coral, row 8, column 8',
    'Empty cell of color Vibrant Coral, row 8, column 9',
    'Empty cell of color Rose Pink, row 9, column 1',
    'Empty cell of color Rose Pink, row 9, column 2',
    'Empty cell of color Rose Pink, row 9, column 3',
    'Empty cell of color Rose Pink, row 9, column 4',
    'Empty cell of color Rose Pink, row 9, column 5',
    'Empty cell of color Lime Yellow, row 9, column 6',
    'Empty cell of color Vibrant Coral, row 9, column 7',
    'Empty cell of color Vibrant Coral, row 9, column 8',
    'Empty cell of color Vibrant Coral, row 9, column 9'
]

export const daDaySquirtleWasBorn = [
  'Empty cell of color Vibrant Coral, row 1, column 1',
    'Empty cell of color Vibrant Coral, row 1, column 2',
    'Empty cell of color Vibrant Coral, row 1, column 3',
    'Empty cell of color Vibrant Coral, row 1, column 4',
    'Empty cell of color Vibrant Coral, row 1, column 5',
    'Queen of color Vibrant Coral, row 1, column 6',
    'Empty cell of color Vibrant Coral, row 1, column 7',
    'Empty cell of color Vibrant Coral, row 1, column 8',
    'Empty cell of color Vibrant Coral, row 1, column 9',
    'Empty cell of color Vibrant Coral, row 2, column 1',
    'Empty cell of color Peach Orange, row 2, column 2',
    'Queen of color Peach Orange, row 2, column 3',
    'Empty cell of color Vibrant Coral, row 2, column 4',
    'Empty cell of color Vibrant Coral, row 2, column 5',
    'Empty cell of color Vibrant Coral, row 2, column 6',
    'Empty cell of color Vibrant Coral, row 2, column 7',
    'Empty cell of color Vibrant Coral, row 2, column 8',
    'Empty cell of color Vibrant Coral, row 2, column 9',
    'Empty cell of color Warm Beige, row 3, column 1',
    'Empty cell of color Pastel Green, row 3, column 2',
    'Empty cell of color Pastel Green, row 3, column 3',
    'Empty cell of color Warm Beige, row 3, column 4',
    'Empty cell of color Vibrant Coral, row 3, column 5',
    'Empty cell of color Warm Beige, row 3, column 6',
    'Empty cell of color Light Gray, row 3, column 7',
    'Empty cell of color Light Gray, row 3, column 8',
    'Empty cell of color Warm Beige, row 3, column 9',
    'Empty cell of color Warm Beige, row 4, column 1',
    'Empty cell of color Pastel Green, row 4, column 2',
    'Empty cell of color Warm Beige, row 4, column 3',
    'Empty cell of color Warm Beige, row 4, column 4',
    'Empty cell of color Warm Beige, row 4, column 5',
    'Empty cell of color Warm Beige, row 4, column 6',
    'Empty cell of color Warm Beige, row 4, column 7',
    'Empty cell of color Light Gray, row 4, column 8',
    'Empty cell of color Warm Beige, row 4, column 9',
    'Empty cell of color Warm Beige, row 5, column 1',
    'Empty cell of color Warm Beige, row 5, column 2',
    'Empty cell of color Warm Beige, row 5, column 3',
    'Empty cell of color Lavender, row 5, column 4',
    'Empty cell of color Lime Yellow, row 5, column 5',
    'Empty cell of color Soft Blue, row 5, column 6',
    'Empty cell of color Warm Beige, row 5, column 7',
    'Empty cell of color Warm Beige, row 5, column 8',
    'Empty cell of color Warm Beige, row 5, column 9',
    'Empty cell of color Rose Pink, row 6, column 1',
    'Empty cell of color Lavender, row 6, column 2',
    'Empty cell of color Lavender, row 6, column 3',
    'Empty cell of color Lavender, row 6, column 4',
    'Empty cell of color Lime Yellow, row 6, column 5',
    'Empty cell of color Soft Blue, row 6, column 6',
    'Empty cell of color Soft Blue, row 6, column 7',
    'Empty cell of color Soft Blue, row 6, column 8',
    'Empty cell of color Rose Pink, row 6, column 9',
    'Empty cell of color Rose Pink, row 7, column 1',
    'Empty cell of color Lavender, row 7, column 2',
    'Empty cell of color Lavender, row 7, column 3',
    'Empty cell of color Lavender, row 7, column 4',
    'Empty cell of color Lime Yellow, row 7, column 5',
    'Empty cell of color Soft Blue, row 7, column 6',
    'Empty cell of color Soft Blue, row 7, column 7',
    'Empty cell of color Rose Pink, row 7, column 8',
    'Empty cell of color Rose Pink, row 7, column 9',
    'Empty cell of color Rose Pink, row 8, column 1',
    'Empty cell of color Lavender, row 8, column 2',
    'Empty cell of color Lavender, row 8, column 3',
    'Empty cell of color Rose Pink, row 8, column 4',
    'Empty cell of color Lime Yellow, row 8, column 5',
    'Empty cell of color Rose Pink, row 8, column 6',
    'Empty cell of color Soft Blue, row 8, column 7',
    'Empty cell of color Soft Blue, row 8, column 8',
    'Empty cell of color Rose Pink, row 8, column 9',
    'Empty cell of color Rose Pink, row 9, column 1',
    'Empty cell of color Rose Pink, row 9, column 2',
    'Empty cell of color Rose Pink, row 9, column 3',
    'Empty cell of color Rose Pink, row 9, column 4',
    'Empty cell of color Rose Pink, row 9, column 5',
    'Empty cell of color Rose Pink, row 9, column 6',
    'Empty cell of color Rose Pink, row 9, column 7',
    'Empty cell of color Rose Pink, row 9, column 8',
    'Empty cell of color Rose Pink, row 9, column 9'
]

export const firstDayInPMac = [
  'Queen of color Vibrant Coral, row 1, column 1',
    'Empty cell of color Vibrant Coral, row 1, column 2',
    'Empty cell of color Vibrant Coral, row 1, column 3',
    'Empty cell of color Vibrant Coral, row 1, column 4',
    'Empty cell of color Vibrant Coral, row 1, column 5',
    'Empty cell of color Vibrant Coral, row 1, column 6',
    'Empty cell of color Vibrant Coral, row 1, column 7',
    'Empty cell of color Vibrant Coral, row 1, column 8',
    'Empty cell of color Vibrant Coral, row 1, column 9',
    'Empty cell of color Vibrant Coral, row 2, column 1',
    'Empty cell of color Peach Orange, row 2, column 2',
    'Queen of color Peach Orange, row 2, column 3',
    'Empty cell of color Vibrant Coral, row 2, column 4',
    'Empty cell of color Vibrant Coral, row 2, column 5',
    'Empty cell of color Vibrant Coral, row 2, column 6',
    'Empty cell of color Vibrant Coral, row 2, column 7',
    'Empty cell of color Vibrant Coral, row 2, column 8',
    'Empty cell of color Vibrant Coral, row 2, column 9',
    'Empty cell of color Peach Orange, row 3, column 1',
    'Empty cell of color Peach Orange, row 3, column 2',
    'Empty cell of color Warm Beige, row 3, column 3',
    'Empty cell of color Warm Beige, row 3, column 4',
    'Empty cell of color Vibrant Coral, row 3, column 5',
    'Empty cell of color Warm Beige, row 3, column 6',
    'Empty cell of color Warm Beige, row 3, column 7',
    'Empty cell of color Vibrant Coral, row 3, column 8',
    'Empty cell of color Vibrant Coral, row 3, column 9',
    'Empty cell of color Peach Orange, row 4, column 1',
    'Empty cell of color Peach Orange, row 4, column 2',
    'Empty cell of color Warm Beige, row 4, column 3',
    'Empty cell of color Warm Beige, row 4, column 4',
    'Empty cell of color Warm Beige, row 4, column 5',
    'Empty cell of color Warm Beige, row 4, column 6',
    'Empty cell of color Warm Beige, row 4, column 7',
    'Empty cell of color Vibrant Coral, row 4, column 8',
    'Empty cell of color Pastel Green, row 4, column 9',
    'Empty cell of color Peach Orange, row 5, column 1',
    'Empty cell of color Light Gray, row 5, column 2',
    'Empty cell of color Light Gray, row 5, column 3',
    'Empty cell of color Warm Beige, row 5, column 4',
    'Empty cell of color Lavender, row 5, column 5',
    'Empty cell of color Warm Beige, row 5, column 6',
    'Empty cell of color Pastel Green, row 5, column 7',
    'Empty cell of color Pastel Green, row 5, column 8',
    'Empty cell of color Pastel Green, row 5, column 9',
    'Empty cell of color Peach Orange, row 6, column 1',
    'Empty cell of color Light Gray, row 6, column 2',
    'Empty cell of color Warm Beige, row 6, column 3',
    'Empty cell of color Warm Beige, row 6, column 4',
    'Empty cell of color Warm Beige, row 6, column 5',
    'Empty cell of color Warm Beige, row 6, column 6',
    'Empty cell of color Warm Beige, row 6, column 7',
    'Empty cell of color Pastel Green, row 6, column 8',
    'Empty cell of color Lime Yellow, row 6, column 9',
    'Empty cell of color Light Gray, row 7, column 1',
    'Empty cell of color Light Gray, row 7, column 2',
    'Empty cell of color Warm Beige, row 7, column 3',
    'Empty cell of color Warm Beige, row 7, column 4',
    'Empty cell of color Soft Blue, row 7, column 5',
    'Empty cell of color Warm Beige, row 7, column 6',
    'Empty cell of color Warm Beige, row 7, column 7',
    'Empty cell of color Lime Yellow, row 7, column 8',
    'Empty cell of color Lime Yellow, row 7, column 9',
    'Empty cell of color Light Gray, row 8, column 1',
    'Empty cell of color Rose Pink, row 8, column 2',
    'Empty cell of color Rose Pink, row 8, column 3',
    'Empty cell of color Rose Pink, row 8, column 4',
    'Empty cell of color Soft Blue, row 8, column 5',
    'Empty cell of color Lime Yellow, row 8, column 6',
    'Empty cell of color Lime Yellow, row 8, column 7',
    'Empty cell of color Lime Yellow, row 8, column 8',
    'Empty cell of color Lime Yellow, row 8, column 9',
    'Empty cell of color Rose Pink, row 9, column 1',
    'Empty cell of color Rose Pink, row 9, column 2',
    'Empty cell of color Rose Pink, row 9, column 3',
    'Empty cell of color Soft Blue, row 9, column 4',
    'Empty cell of color Soft Blue, row 9, column 5',
    'Empty cell of color Soft Blue, row 9, column 6',
    'Empty cell of color Lime Yellow, row 9, column 7',
    'Empty cell of color Lime Yellow, row 9, column 8',
    'Empty cell of color Lime Yellow, row 9, column 9'
]

export default hello;
